# chai-conge-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: chai-conge
  namespace: chai
spec:
  selector:
    app: chai-conge
  ports:
  - protocol: TCP
    port: 80        # port interne Kubernetes
    targetPort: 3000 # port du container